version: '3.7'

services:
  push-redis:
    image: pushaas/push-redis:1
    ports:
      - "6379:6379"

  push-stream:
    image: pushaas/push-stream:1
    ports:
      - "9080:9080"

  push-agent:
    image: pushaas/push-agent:1
    depends_on:
      - push-redis
      - push-stream
    environment:
      PUSHAGENT_REDIS__URL: "redis://push-redis:6379"
      PUSHAGENT_PUSH_STREAM__URL: "http://push-stream:9080"

  push-api:
    image: pushaas/push-api:1
    ports:
      - "8080:8080"
    depends_on:
      - push-redis
      - push-stream
    environment:
      PUSHAPI_REDIS__URL: "redis://push-redis:6379"
      PUSHAPI_PUSH_STREAM__URL: "http://push-stream:9080"
